# =========================================================
# Universal GitHub Pages deployment template
# for AIDA64 Gauge Generator versions (v2, v3, test, etc.)
# =========================================================

name: Deploy <VERSION> to /<VERSION> subfolder

# 🟢 Change this to match your branch name
# Example: [ v3 ]  or  [ test ]
on:
  push:
    branches: [ <VERSION> ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Build your project
      - run: npm ci
      - run: npm run build

      # Deploy to gh-pages/<VERSION>
      - name: Deploy to gh-pages/<VERSION>
        run: |
          VERSION="<VERSION>"

          # Temp build copy
          mkdir temp-build
          cp -r dist/* temp-build/

          # Prepare gh-pages branch
          git fetch origin gh-pages
          git worktree add gh-pages-branch gh-pages
          cd gh-pages-branch

          # Replace /<VERSION>/ content
          mkdir -p $VERSION
          rm -rf $VERSION/*
          cp -r ../temp-build/* $VERSION/

          # Commit and push
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $VERSION
          git commit -m "Update $VERSION build $(date)" || echo "No changes to commit"
          git push origin gh-pages
